2021/01/31 15:49:22 Attempt 1 of http call to http://10.0.0.5:16384/sendlogstoartifacts/info
2021/01/31 15:49:22 Attempt 1 of http call to http://10.0.0.5:16384/sendlogstoartifacts/status
[2021-01-31T15:49:23.775876] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['main.py', '--dense_units', '32', '--dropout', '0.44366898730495014', '--epochs', '230', '--filter1', '16', '--filter2', '96', '--filter3', '102'])
Script type = None
Starting the daemon thread to refresh tokens in background for process with pid = 100
Entering Run History Context Manager.
[2021-01-31T15:49:26.390625] Current directory: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-136718/azureml/hd_ef1aecef-04dc-4da0-8394-abb5844e3cb0_3/mounts/workspaceblobstore/azureml/HD_ef1aecef-04dc-4da0-8394-abb5844e3cb0_3
[2021-01-31T15:49:26.391171] Preparing to call script [main.py] with arguments:['--dense_units', '32', '--dropout', '0.44366898730495014', '--epochs', '230', '--filter1', '16', '--filter2', '96', '--filter3', '102']
[2021-01-31T15:49:26.396531] After variable expansion, calling script [main.py] with arguments:['--dense_units', '32', '--dropout', '0.44366898730495014', '--epochs', '230', '--filter1', '16', '--filter2', '96', '--filter3', '102']

/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Found 251 images belonging to 3 classes.
Found 66 images belonging to 3 classes.
WARNING:tensorflow:From /azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1 (Conv2D)               (None, 254, 254, 16)      160       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 127, 127, 16)      0         
_________________________________________________________________
conv2 (Conv2D)               (None, 125, 125, 16)      2320      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 62, 62, 16)        0         
_________________________________________________________________
dropout (Dropout)            (None, 62, 62, 16)        0         
_________________________________________________________________
conv3 (Conv2D)               (None, 60, 60, 96)        13920     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 20, 20, 96)        0         
_________________________________________________________________
conv4 (Conv2D)               (None, 18, 18, 102)       88230     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 6, 6, 102)         0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 6, 6, 102)         0         
_________________________________________________________________
flatten (Flatten)            (None, 3672)              0         
_________________________________________________________________
dense (Dense)                (None, 32)                117536    
=================================================================
Total params: 222,166
Trainable params: 222,166
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:From /azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2021-01-31 15:49:28.507321: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-01-31 15:49:28.513102: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2596990000 Hz
2021-01-31 15:49:28.513875: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55729a1bb380 executing computations on platform Host. Devices:
2021-01-31 15:49:28.513924: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Epoch 1/230
Starting the daemon thread to refresh tokens in background for process with pid = 100


[2021-01-31T15:49:28.818507] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
2 items cleaning up...
Cleanup took 0.11583781242370605 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 100
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    main()
  File "main.py", line 104, in main
    history = model.fit(x=train_gen, epochs=args.epochs)#, workers=6, use_multiprocessing=True)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 737, in fit
    initial_epoch=initial_epoch)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 177, in model_iteration
    batch_data = _get_next_batch(output_generator, mode)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 258, in _get_next_batch
    generator_output = next(output_generator)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 655, in get
    six.reraise(*sys.exc_info())
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 649, in get
    inputs = self.queue.get(block=True).get()
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 445, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/keras_preprocessing/image/iterator.py", line 65, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/keras_preprocessing/image/iterator.py", line 230, in _get_batches_of_transformed_samples
    interpolation=self.interpolation)
  File "/azureml-envs/azureml_a4a25a3895e798d70face8edda93b5da/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 111, in load_img
    raise ImportError('Could not import PIL.Image. '
ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.

[2021-01-31T15:49:34.164469] Finished context manager injector with Exception.
2021/01/31 15:49:35 Failed to parse control script error: /mnt/batch/tasks/workitems/7d780669-ab9f-4631-ad53-78c9a345ce45/job-1/hd_ef1aecef-04dc-4da_4807596d-590e-4a27-8e26-8dcddce9e634/wd/runTaskLetTask_error.json to json File /mnt/batch/tasks/workitems/7d780669-ab9f-4631-ad53-78c9a345ce45/job-1/hd_ef1aecef-04dc-4da_4807596d-590e-4a27-8e26-8dcddce9e634/wd/runTaskLetTask_error.json doesn't exist
2021/01/31 15:49:35 Failed to run the wrapper cmd with err: exit status 1
2021/01/31 15:49:35 Attempt 1 of http call to http://10.0.0.5:16384/sendlogstoartifacts/status
2021/01/31 15:49:35 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2021/01/31 15:49:35 MPI publisher: intel ; version: 2018
2021/01/31 15:49:35 Process Exiting with Code:  1
